### ISSUE TITLE
Interactive Grid: field validations stop icon picker popup

### ISSUE THREAD

**Issue by jeffreykemp** [grlicaa/IconPicker#1]
For example, if there are other required fields in the grid, they will be highlighted red and the icon picker popup won't appear.

Not a big issue (user just needs to enter the other required fields first) but if this can be fixed it would improve usability.

APEX 18.2.0.00.12

**Comment by grlicaa** [comment]
Hi Jeffrey,

I tried to reproduce your error but without luck....for me works in every case "APEX 18.2.0.00.12"
![image](https://user-images.githubusercontent.com/30799807/57569118-9cb58d80-73f0-11e9-9ddf-d3222c5f58fe.png)

Whenever I click on popup icon it works fine....
Can you please put some sample with described error it wold be of big help.

Thanks,
Br,
Andrej

**Comment by jeffreykemp** [comment]
I think it might only be a problem when the plugin is set to "show icon only". I'll see if I can set up a test case.

**Comment by grlicaa** [comment]
Not sure but maybe was connected with 
javascript error: "Uncaught TypeError: $(...).iconList is not a function  error.... probably...
If you find the case please do tell.... tnx
